---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wger-nginx-config
data:
  nginx.conf: |
    upstream wger {
        server localhost:8000;
    }

    server {
        listen 80;

        location /static/ {
            alias /wger/static/;
        }

        location /media/ {
            alias /wger/media/;
        }

        location / {
            proxy_pass http://wger;
            proxy_set_header Host $http_host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
            proxy_set_header X-Forwarded-Host $http_host;
            proxy_redirect off;
        }

        client_max_body_size 100M;
    }
