---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wger-secrets
  namespace: self-hosted
spec:
  refreshInterval: "10m"
  target:
    name: wger-secrets
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        secret-key: |-
          {{ .WGER_SECRET_KEY }}
        signing-key: |-
          {{ .WGER_SIGNING_KEY }}
  data:
    - secretKey: WGER_SECRET_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        # Item called "Self Hosted"
        key: 6abe895f-83ea-4e1d-9610-a9324093d608
        property: WGER_SECRET_KEY
    - secretKey: WGER_SIGNING_KEY
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        # Item called "Self Hosted"
        key: 6abe895f-83ea-4e1d-9610-a9324093d608
        property: WGER_SIGNING_KEY
