apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: patch-nfd-worker-nixos
spec:
  background: false
  validationFailureAction: Audit  # This will log but not block
  rules:
    - name: fix-lib-modules-path-for-nixos
      match:
        any:
          - resources:
              kinds:
                - Pod
              namespaces:
                - system
              names:
                - node-feature-discovery-worker-*
      mutate:
        patchStrategicMerge:
          spec:
            volumes:
              - name: host-lib
                hostPath:
                  path: /run/current-system/kernel-modules/lib