---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: kanboard-volsync-minio
  namespace: self-hosted
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: kanboard-volsync-minio
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RESTIC_REPOSITORY: "s3:https://s3.internal/volsync-volumes/kanboard"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: 4c7bab21-8e2d-49ee-9762-4d27130790c9
        property: RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: 4c7bab21-8e2d-49ee-9762-4d27130790c9
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: 4c7bab21-8e2d-49ee-9762-4d27130790c9
        property: AWS_SECRET_ACCESS_KEY
