apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: kanboard
spec:
  # The PVC to sync
  sourcePVC: kanboard
  # MIGRATION: Paused during Minio â†’ Garage migration
  paused: true
  # trigger:
  #   # Synchronize every 6 hours
  #   schedule: "0 */6 * * *"
  restic:
    customCA:
      configMapName: kanboard-volsync-ca
      key: ca.crt
    copyMethod: Snapshot
    repository: kanboard-volsync-garage
    storageClassName: "longhorn"
    volumeSnapshotClassName: "longhorn-snapshot-vsc"
    moverSecurityContext:
      runAsUser: 100
      runAsGroup: 101
      fsGroup: 101
    pruneIntervalDays: 7
    retain:
      hourly: 24
      daily: 7
      weekly: 5