---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: immich-cache
  namespace: media
spec:
  sourcePVC: immich-cache
  trigger:
    schedule: "0 * * * *"  # Hourly backups
  restic:
    copyMethod: Snapshot
    pruneIntervalDays: 7
    repository: immich-volsync-garage
    volumeSnapshotClassName: longhorn-snapshot-vsc
    storageClassName: longhorn
    cacheStorageClassName: longhorn
    cacheCapacity: 2Gi
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    retain:
      hourly: 24
      daily: 7
      weekly: 4
    customCA:
      configMapName: immich-volsync-ca
      key: ca.crt
