apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager-issuers
  namespace: argocd
spec:
  project: default
  sources:
    - path: kubernetes/base/infra/cert-manager/issuers
      repoURL: 'https://forge.internal/nemo/avalanche.git'
      targetRevision: HEAD
  destination:
    namespace: cert-manager
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true