apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://forge.internal/nemo/avalanche.git
      targetRevision: HEAD
      ref: values
    - repoURL: oci://quay.io/jetstack/charts/cert-manager
      targetRevision: v1.19.2
      path: .
      helm:
        releaseName: cert-manager
        valueFiles:
          - $values/kubernetes/base/infra/cert-manager/cert-manager/helm-values.yaml
  destination:
    namespace: cert-manager
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true