apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: barman-cloud-plugin
  namespace: argocd
spec:
  project: default
  source:
    path: kubernetes/base/apps/cnpg-system/barman-cloud-plugin
    repoURL: 'https://forge.internal/nemo/avalanche.git'
    targetRevision: HEAD
  destination:
    namespace: cnpg-system
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true