---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: archivebox-volsync-minio
  namespace: media
spec:
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: archivebox-volsync-minio
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "{{ .RESTIC_REPOSITORY }}"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: RESTIC_REPOSITORY
      remoteRef:
        key: 4c7bab21-8e2d-49ee-9762-4d27130790c9
        property: RESTIC_REPOSITORY
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: 4c7bab21-8e2d-49ee-9762-4d27130790c9
        property: RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: 4c7bab21-8e2d-49ee-9762-4d27130790c9
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: 4c7bab21-8e2d-49ee-9762-4d27130790c9
        property: AWS_SECRET_ACCESS_KEY
  dataFrom:
    - extract:
        key: 4c7bab21-8e2d-49ee-9762-4d27130790c9
