---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: archivebox-bootstrap
  namespace: media
spec:
  trigger:
    manual: restore-once
  restic:
    repository: archivebox-volsync-minio
    destinationPVC: archivebox-bootstrap
    storageClassName: longhorn
    accessModes:
      - ReadWriteMany
    capacity: 2Gi
    copyMethod: Snapshot
    volumeSnapshotClassName: longhorn
    cacheStorageClassName: longhorn
    cacheCapacity: 2Gi
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    customCA:
      configMapName: archivebox-volsync-ca
      key: ca.crt
