---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: miniflux
  labels:
    app: miniflux
spec:
  replicas: 1
  selector:
    matchLabels:
      app: miniflux
  template:
    metadata:
      labels:
        app: miniflux
    spec:
      containers:
      - name: miniflux
        image: ghcr.io/miniflux/miniflux:2.2.17@sha256:802ab7d045826d047883476e2310bf59f5d9b3875f7a8106fa0c43638d01fd64
        envFrom:
          - secretRef:
              name: miniflux-admin-user-secret
        env:
          - name: "BASE_URL"
            value: "https://miniflux.internal"
          - name: "CREATE_ADMIN"
            value: "1"
          - name: "DATABASE_URL"
            valueFrom:
              secretKeyRef:
                name: miniflux-16-db-app
                key: uri
          - name: "DEBUG"
            value: "1"
          - name: "LOG_DATE_TIME"
            value: "1"
          - name: "POLLING_SCHEDULER"
            value: "entry_frequency"
          - name: "POLLING_FREQUENCY"
            value: "15"
          - name: "RUN_MIGRATIONS"
            value: "1"
        ports:
          - containerPort: 8080
            name: http-miniflux
        resources:
          requests:
            cpu: 12m
            memory: 64M
          limits:
            memory: 256M
        livenessProbe:
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 1
          failureThreshold: 3
          httpGet:
            path: /healthcheck
            port: 8080
