---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-operator-oauth
  namespace: network
spec:
  refreshInterval: "10m"
  target:
    name: operator-oauth
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        client_id: |-
          {{ .TAILSCALE_OAUTH_CLIENT_ID }}
        client_secret: |-
          {{ .TAILSCALE_OAUTH_CLIENT_SECRET }}
  data:
    - secretKey: TAILSCALE_OAUTH_CLIENT_ID
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        # "Tailscale" item in Bitwarden
        key: "b969cbd1-4545-4ce7-ab9a-ce48aab9420e"
        property: TAILSCALE_OAUTH_CLIENT_ID
    - secretKey: TAILSCALE_OAUTH_CLIENT_SECRET
      sourceRef:
        storeRef:
          name: bitwarden-fields
          kind: ClusterSecretStore
      remoteRef:
        # "Tailscale" item in Bitwarden
        key: "b969cbd1-4545-4ce7-ab9a-ce48aab9420e"
        property: TAILSCALE_OAUTH_CLIENT_SECRET
