apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: marmithon
  namespace: argocd
spec:
  project: default
  source:
    path: kubernetes/base/apps/irc/marmithon
    repoURL: 'https://forge.internal/nemo/avalanche.git'
    targetRevision: HEAD
  destination:
    namespace: irc
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true