---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: thelounge-ingress
  annotations:
    gethomepage.dev/description: IRC web client
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Chat
    gethomepage.dev/icon: thelounge.png
    gethomepage.dev/name: The Lounge
    gethomepage.dev/pod-selector: "app=thelounge"
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: ca-server-cluster-issuer
    cert-manager.io/common-name: irc.internal
spec:
  tls:
    - hosts:
      - irc.internal
      secretName: thelounge-ing-cert
  ingressClassName: nginx
  rules:
  - host: irc.internal
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: thelounge
            port:
              number: 9000
