apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://forge.internal/nemo/avalanche.git
      targetRevision: HEAD
      ref: values
    - chart: kyverno
      repoURL: oci://ghcr.io/kyverno/charts
      targetRevision: 3.5.2
      helm:
        releaseName: kyverno
        valueFiles:
          - $values/kubernetes/base/infra/kyverno/kyverno/helm-values.yaml
  destination:
    namespace: kyverno
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
