apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bitwarden-store
  namespace: argocd
spec:
  project: default
  source:
    path: kubernetes/base/infra/security/bitwarden
    repoURL: https://forge.internal/nemo/avalanche.git
    targetRevision: HEAD
  destination:
    namespace: security
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true