---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: immich-external-store
spec:
  configuration:
    destinationPath: s3://cloudnative-pg/
    endpointURL: https://s3.garage.internal
    endpointCA:
      name: cnpg-garage-access-immich
      key: tls.crt
    s3Credentials:
      accessKeyId:
        name: cnpg-garage-access-immich
        key: aws-access-key-id
      secretAccessKey:
        name: cnpg-garage-access-immich
        key: aws-secret-access-key
      region:
        name: cnpg-garage-access-immich
        key: s3-region
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 8
