---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

components:
  - ../../components/common

resources:
  - namespace.yaml
  # Applications
  # - ./home-assistant/ks.yaml # Migrated to ArgoCD
  # - ./rtlamr2mqtt/ks.yaml
  # - ./esphome/ks.yaml # Migrated to ArgoCD
  # - ./nut-upsd/ks.yaml
  # - ./rtl433/ks.yaml
  # - ./zwave/ks.yaml # Migrated to ArgoCD
  # - ./mqtt/ks.yaml # Migrated to ArgoCD
