---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: wikijs-backup-store
spec:
  configuration:
    destinationPath: s3://cloudnative-pg/
    endpointURL: https://s3.internal
    endpointCA:
      name: cnpg-minio-access-wikijs
      key: tls.crt
    s3Credentials:
      accessKeyId:
        name: cnpg-minio-access-wikijs
        key: aws-access-key-id
      secretAccessKey:
        name: cnpg-minio-access-wikijs
        key: aws-secret-access-key
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 8
  retentionPolicy: "30d"