# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: home-automation
resources:
- objectstore-backup.yaml
- objectstore-external.yaml
- pg-cluster-16.yaml
- scheduledbackup.yaml
