---
apiVersion: barmancloud.cnpg.io/v1
kind: ObjectStore
metadata:
  name: hass-external-store
  namespace: home-automation
spec:
  configuration:
    destinationPath: s3://cloudnative-pg/
    endpointURL: https://s3.garage.internal
    endpointCA:
      name: cnpg-garage-access-hass
      key: tls.crt
    s3Credentials:
      accessKeyId:
        name: cnpg-garage-access-hass
        key: aws-access-key-id
      secretAccessKey:
        name: cnpg-garage-access-hass
        key: aws-secret-access-key
    data:
      compression: bzip2
    wal:
      compression: bzip2
      maxParallel: 8