---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: esphome-volsync-garage
  namespace: home-automation
spec:
  refreshInterval: 15m
  secretStoreRef:
    name: bitwarden-fields
    kind: ClusterSecretStore
  target:
    name: esphome-volsync-garage
    deletionPolicy: Delete
    template:
      type: Opaque
      data:
        RESTIC_REPOSITORY: "s3:https://s3.garage.internal/volsync-volumes/esphome"
        RESTIC_PASSWORD: "{{ .RESTIC_PASSWORD }}"
        AWS_ACCESS_KEY_ID: "{{ .AWS_ACCESS_KEY_ID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .AWS_SECRET_ACCESS_KEY }}"
  data:
    - secretKey: RESTIC_PASSWORD
      remoteRef:
        key: b45f65b2-6326-42b8-b159-0e630fd223db
        property: RESTIC_PASSWORD
    - secretKey: AWS_ACCESS_KEY_ID
      remoteRef:
        key: b45f65b2-6326-42b8-b159-0e630fd223db
        property: AWS_ACCESS_KEY_ID
    - secretKey: AWS_SECRET_ACCESS_KEY
      remoteRef:
        key: b45f65b2-6326-42b8-b159-0e630fd223db
        property: AWS_SECRET_ACCESS_KEY
