---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: secondbrain-16-db
spec:
  schedule: "@daily"
  method: plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  immediate: true
  backupOwnerReference: self
  cluster:
    name: secondbrain-16-db
