apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-vip
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://forge.internal/nemo/avalanche.git
    targetRevision: HEAD
    path: kubernetes/base/infra/system/kube-vip
  destination:
    namespace: kube-system
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
