apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://forge.internal/nemo/avalanche.git
      targetRevision: HEAD
      ref: values
    - chart: node-feature-discovery
      repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
      targetRevision: 0.18.3
      helm:
        releaseName: node-feature-discovery
        valueFiles:
          - $values/kubernetes/base/infra/system/nfd/helm-values.yaml
    - repoURL: https://forge.internal/nemo/avalanche.git
      targetRevision: HEAD
      path: kubernetes/base/infra/system/nfd
  destination:
    namespace: system
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true