apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://forge.internal/nemo/avalanche.git
      targetRevision: HEAD
      ref: values
    - path: .
      repoURL: oci://ghcr.io/piraeusdatastore/helm-charts/snapshot-controller
      targetRevision: 5.0.2
      helm:
        releaseName: snapshot-controller
        valueFiles:
          - $values/kubernetes/base/infra/system/snapshot-controller/helm-values.yaml
  destination:
    namespace: system
    name: 'in-cluster'
  ignoreDifferences:
    - group: ""
      kind: Secret
      name: snapshot-controller-conversion-webhook
      namespace: system
      jsonPointers:
        - /data
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      name: volumegroupsnapshotcontents.groupsnapshot.storage.k8s.io
      jsonPointers:
        - /spec/conversion/webhook/clientConfig/caBundle
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true