apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: snapshot-controller
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://forge.internal/nemo/avalanche.git
      targetRevision: HEAD
      ref: values
    - path: .
      repoURL: oci://ghcr.io/piraeusdatastore/helm-charts/snapshot-controller
      targetRevision: 5.0.1
      helm:
        releaseName: snapshot-controller
        valueFiles:
          - $values/kubernetes/base/infra/system/snapshot-controller/helm-values.yaml
  destination:
    namespace: system
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true