apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: volsync
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://forge.internal/nemo/avalanche.git
      targetRevision: HEAD
      ref: values
    - chart: volsync
      repoURL: https://perfectra1n.github.io/volsync/charts/
      targetRevision: 0.18.3
      helm:
        releaseName: volsync
        valueFiles:
          - $values/kubernetes/base/infra/system/volsync/helm-values.yaml
  destination:
    namespace: system
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true