---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: grafana-sidecar
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: grafana-sidecar
rules:
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: grafana-sidecar
subjects:
  - kind: ServiceAccount
    name: grafana-sidecar
    namespace: home-automation
roleRef:
  kind: ClusterRole
  name: grafana-sidecar
  apiGroup: rbac.authorization.k8s.io
