# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: media
resources:
- db
- redis
- storage
- server
- web
- microservices
- machine-learning
- volsync-ca-configmap.yaml
- ingress.yaml
