---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ntfy-ingress
  annotations:
    gethomepage.dev/description: Push notifications
    gethomepage.dev/enabled: "true"
    gethomepage.dev/group: Self-Hosted
    gethomepage.dev/icon: ntfy
    gethomepage.dev/name: ntfy
    gethomepage.dev/pod-selector: "app=ntfy"
    cert-manager.io/cluster-issuer: ca-server-cluster-issuer
    cert-manager.io/common-name: ntfy.internal
spec:
  tls:
    - hosts:
        - ntfy.internal
      secretName: ntfy-ing-cert
  ingressClassName: nginx
  rules:
    - host: ntfy.internal
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ntfy
                port:
                  number: 80
