---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: n8n-16-db
spec:
  schedule: "@daily"
  method: plugin  # Use Barman Cloud Plugin
  pluginConfiguration:
    name: barman-cloud.cloudnative-pg.io
  immediate: true
  backupOwnerReference: self
  cluster:
    name: n8n-16-db
