---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: mqtt
  namespace: home-automation
spec:
  sourcePVC: mqtt
  # MIGRATION: Suspended during Minio â†’ Garage migration
  suspend: true
  # trigger:
  #   schedule: "0 * * * *"
  restic:
    customCA:
      configMapName: mqtt-volsync-ca
      key: ca.crt
    copyMethod: Snapshot
    repository: mqtt-volsync-minio
    storageClassName: "longhorn"
    volumeSnapshotClassName: "longhorn-snapshot-vsc"
    cacheCapacity: "2Gi"
    moverSecurityContext:
      runAsUser: 1000
      runAsGroup: 1000
      fsGroup: 1000
    pruneIntervalDays: 14
    retain:
      hourly: 24
      daily: 7
    accessModes: [ "ReadWriteOnce" ]
