---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minecraft
  namespace: argocd
spec:
  project: default
  source:
    path: kubernetes/base/apps/games/minecraft
    repoURL: https://forge.internal/nemo/avalanche.git
    targetRevision: HEAD
  destination:
    namespace: games
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
