---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb2
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://forge.internal/nemo/avalanche.git
    targetRevision: main
    path: kubernetes/base/apps/home-automation/influxdb2
    plugin:
      name: kustomize-envsubst
      env:
        - name: APP
          value: influxdb2
        - name: VOLSYNC_CAPACITY
          value: "10Gi"
        - name: VOLSYNC_BITWARDEN_KEY
          value: "b45f65b2-6326-42b8-b159-0e630fd223db"
        - name: VOLSYNC_STORAGECLASS
          value: longhorn
        - name: VOLSYNC_ACCESSMODE
          value: ReadWriteOnce
        - name: VOLSYNC_CACHE_CAPACITY
          value: "4Gi"
        - name: VOLSYNC_SCHEDULE
          value: "0 * * * *"
        - name: VOLSYNC_UID
          value: "1000"
        - name: VOLSYNC_GID
          value: "1000"
  ignoreDifferences:
    # PVC was created manually during migration; dataSourceRef is immutable
    # and harmless to ignore (only used on initial PVC creation for restore)
    - group: ""
      kind: PersistentVolumeClaim
      name: influxdb2
      jsonPointers:
        - /spec/dataSourceRef
        - /spec/dataSource
  destination:
    server: https://kubernetes.default.svc
    namespace: home-automation
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
