---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - influxdb2-app.yaml
  - rtl433-app.yaml
  - grafana-app.yaml
  - rtlamr2mqtt-app.yaml
  - nut-upsd-app.yaml
