apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rtlamr2mqtt
  namespace: argocd
spec:
  project: default
  sources:
    - path: kubernetes/base/apps/home-automation/rtlamr2mqtt
      repoURL: https://forge.internal/nemo/avalanche.git
      targetRevision: HEAD
      ref: values
    - repoURL: oci://ghcr.io/bjw-s/helm/app-template
      targetRevision: 3.7.3
      path: .
      helm:
        releaseName: rtlamr2mqtt
        valueFiles:
          - $values/kubernetes/base/apps/home-automation/rtlamr2mqtt/helm-values.yaml
  destination:
    namespace: home-automation
    name: 'in-cluster'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true